### ISSUE TITLE
feature request: align header info

### ISSUE THREAD

**Issue by shoichiaizawa** [alpertuna/vim-header#11]
This may only be my preference but I was wondering if adding a feature for aligning header lines was easily implemented or not.

What I meant by this is that, currently when you perform `:AddHeader`, you get the following header:

```
# File: filename.extension
# Author: Firstname Lastname <username@example.com>
# Date: d.m.Y
# Last Modified: 2017-06-27

```

Instead, I would like to have the following header:

```
# File:          filename.extension
# Author:        Firstname Lastname <username@example.com>
# Date:          d.m.Y
# Last Modified: 2017-06-27

```

What do you think about this?

**Comment by alpertuna** [comment]
It is possible to implement and can be beneficial for many users. I'll add this feature soon.

**Comment by anchnk** [comment]
Hey I just came up with a working version of this feature.
It allows to switch between non aligned headers and aligned ones.
It's build dynamically, I just need to test it a bit further and clean up the code as well as rebase your latest changes @alpertuna but we should have that landing soon.

**Comment by alpertuna** [comment]
Thanks @anchnk for giving a hand my place for this feature
