### ISSUE TITLE
feature request: supports for cfg filetype

### ISSUE THREAD

**Issue by anchnk** [alpertuna/vim-header#19]
I am willing to contribute and add `cfg` `filetype` supports to `vim-header`. This should be straightforward. 
However, I would just like your opinion on one point: 

It seems that `cfg` files (standing for configuration files) accepts `#`, `;` and `//` as char for comments. Should we choose a default comment character ? Or should we expose an option to select between those 3 ?

I know that for instance `dunstrc` files are detected as being configuration files.

Just wanted your opinions before starting the fork.

**Comment by alpertuna** [comment]
Hi @anchnk,
`cfg` file type has vary comment characters as you know. And as you say, it can be done by adding a property to let user change the char. For example by adding `let g:cfg_comment_char=` in `.vimrc`. And `#` may be default char.
If you want to code it, it is welcome :blush: Also thanks for asking my opinion.

**Comment by anchnk** [comment]
Hello @alpertuna,

Thank you for your detailed answer.
So a correct way of handling this would be:

1. check if the option `g:cfg_comment_char` is set.
1.1 If not, Use `#` as default character
1.2 Else
2. (Opt, not sure if it's needed) Check if it's a valid char
2.1 If not, use default `#` ?
2.2 If it is, use it's value as `b:comment_char`'s value.

If you agree with that behavior I am going to implement it asap

**Comment by alpertuna** [comment]
Thanks for preparing pseudo code and asking me.

I think validation is unnecessary because there may be different comment types that we think that is invalid.
And for option name I misled. If we name the option as `header_cfg_comment_char`, it would better because all options have this prefix.

And happy coding :blush:
