### ISSUE TITLE
E492: Not an editor command: AddHeader

### ISSUE THREAD

**Issue by pwyq** [alpertuna/vim-header#29]
Operating System: Ubuntu 16.04

What I did:
I cloned this repo to `~/.vim/bundle` and add author and email in the `.vimrc`.

The problem:
When I pressed `F4` in a testing file, it gave me `E492: Not an editor command: AddHeader`.

What I tried:
I tried to google this issue, and I found [this one](https://github.com/VundleVim/Vundle.vim/issues/486). I also created a symlink of `~/.vim/.vimrc` to `~/.vimrc`. I am not sure if this problem is a result of 2 `.vimrc` file; I tried to delete the `~/.vimrc`, the problem still exists.

Any help are appreciated!

**Comment by alpertuna** [comment]
Hi @pwyq,
Firstly I need to know which plugin manager do you use or are you using?

That link you found is about [vundle](https://github.com/VundleVim/Vundle.vim) plugin manager.
However cloning repo to `~/.vim/bundle` is the procedure of [pathogen](https://github.com/tpope/vim-pathogen) plugin manager.
And yes `~/.vimrc` is correct location.

**Comment by pwyq** [comment]
Hi, I'm new to Vim.
I think I haven't installed any plugin manager.

**Comment by alpertuna** [comment]
Ok, In this case you can use pathogen since It is quite easy. Just apply these install steps; [Pathogen Installation](https://github.com/tpope/vim-pathogen#installation). After that, plugins under `~/.vim/bundle` directory will be automaticaly loaded by pathogen.

**Comment by pwyq** [comment]
Thank you so much! It worked.

**Comment by alpertuna** [comment]
You're welcome :blush:
