### ISSUE TITLE
Critical bug when update header

### ISSUE THREAD

**Issue by wfxr** [alpertuna/vim-header#31]
When updating the header, the plugin try to replace **every** places which contains string like `File`, `Last Modified Date` etc.
eg:

```bash
#!/bin/bash
# File              : t.sh
# Author            : xxx <xxx@gmail.com>
# Date              : 20.11.2017
# Last Modified Date: 20.11.2017
# Last Modified By  : xxx <xxx@gmail.com>

function FileReader() {
}
function FileParser() {
}
```

When press `F4` or save the file, the content become as this:
```bash
#!/bin/bash
# File              : t.sh
# Author            : xxx <xxx@gmail.com>
# Date              : 20.11.2017
# Last Modified Date: 20.11.2017
# Last Modified By  : xxx <xxx@gmail.com>

function File              : t.sh
function File              : t.sh
}
```

It's horrible if I edit the file not int VCS...

**Comment by alpertuna** [comment]
Hi @wfxr,
To prevent this, there is an option named [g:header_max_size](https://github.com/alpertuna/vim-header#gheader_max_size). But its default value is `7`. Either you set it higher value, or your `vim-header` plugin is not up to date.

**Comment by wfxr** [comment]
@alpertuna Strange... I checked the plugin version and make sure it is the newest version(`commit ea85537d5012f4c269951eb2caf56e3eda4ac797`).  I set the g:header_max_size in vimrc and the thing doesn't change. 
My vimrc:
Plug 'alpertuna/vim-header'
let g:header_field_author = 'wenxuan'
let g:header_field_author_email = 'wenxuangm@gamil.com'
let g:header_max_size = 7
map <F4> :AddHeader<CR>

**Comment by wfxr** [comment]
`g:header_max_size` is a workaround if worked. But maybe we should restrain the replace patterns to avoid this?

**Comment by alpertuna** [comment]
I will inspect the `header_max_size` issue. And restraining the pattern is also needed as you say.

**Comment by JulHee** [comment]
Hi,

I am not sure if this completely solves the problem but limiting the substitute command to specific lines solves the problem in my files.

**Line 287 **
`
execute '%s/' . field . '/' . field_add . s:create_pattern_text(a:value) .'/'
to 
execute '0,'. g:header_max_size .'s/' . field . '/' . field_add . s:create_pattern_text(a:value) .'/'
`
and  **Line 295**
`
execute '%s/' . l:field_without_spaces . '/' . a:field . '/'
to 
execute '0,'. g:header_max_size .'s/' . l:field_without_spaces . '/' . a:field . '/'
`

I hope this helps.

**Comment by wfxr** [comment]
@JulHee That works.
Why not create a PR?

**Comment by JulHee** [comment]
I am fairly new to using GitHub for more than own project so I hope I made everything right with the Pull request.

**Comment by alpertuna** [comment]
It makes sense, thank you @JulHee, and PR is ok :blush:
I was not able to inspect sorry for that. However it seems, it was using `g:header_max_size` option just for looking for does any header exist. And if it is true it was replacing all document.
