### ISSUE TITLE
Could add AGPL license ?

### ISSUE THREAD

**Issue by mwolff44** [alpertuna/vim-header#35]
Hi. Thanks for this vim plugin. 
Could you add LGPL v3 licence ? Giw can I do that ?
Thanks
Mathias

**Comment by alpertuna** [comment]
Hi @mwolff44,
LGPL v3 license text is really long to put it as a file header. It looks it is suitable to put in an individual "COPYRIGHT" file. However if it is used or you use as a header I can also add this license.
