### ISSUE TITLE
disable g:header_auto_add_header for some files

### ISSUE THREAD

**Issue by x4m3** [alpertuna/vim-header#38]
hi,  
im writing a website with jekyll and i use vim and vim-header, and i have `g:header_auto_add_header` set to default value (which is 1), no big deal for every files.

however, jekyll doesnt like to have comments before its markup.

my question is: is it possible to disable vim-header for some files? or there's a work around?  
in the meantime, i have the headers, close vim and use vi to remove them manually.

i hope im clear enough.

thank you

**Comment by TC500** [comment]
add the line to your vimrc,you can add any file type you want.
let g:header_auto_add_header=0
autocmd BufNewFile *.cpp,*.c,*.h,*.hpp,*.cc,*.cxx,*.py *.html call header#add_header(0, 0, 1)
autocmd BufWritePre *.cpp,*.c,*.h,*.hpp,*.cc,*.cxx,*.py *.html silent! :AddHeader

**Comment by TC500** [comment]
add the lines to your vimrc, you can add any file ext you want.
autocmd BufNewFile \*.cpp,\*.c,\*.h,\*.hpp,\*.cc,\*.cxx,\*.py call header#add_header(0, 0, 1)
autocmd BufWritePre \*.cpp,\*.c,\*.h,\*.hpp,\*.cc,\*.cxx,\*.py silent! :AddHeader

**Comment by JulHee** [comment]
Shouldn't it be easier to just disable `g:header_auto_add_header`when editing jekyll ?

`au BufReadPost,BufNewFile *.md let g:header_auto_add_header=0`

**Comment by x4m3** [comment]
@TC500 ohh that would work!  
even better : would it be possible to replace file extensions by a path? for example `~/my-jekyll-blog/` ?

**Comment by x4m3** [comment]
@JulHee nice, that's even cleaner than the first one! can i add multiple file extensions and/or a full path? like `~/my-jekyll-blog/`

**Comment by alpertuna** [comment]
I think it is not an issue any more, as vimrc native options handle it

**Comment by Xaelias** [comment]
Hey y'all, I found this because I'm trying to do exactly this for "markdown" files (`*.md`) and... i don't seem to be able to get it to take.
I've tried to add the following to my `~/.vimrc` but neither work:
```
au BufNewFile,BufRead *.md let g:header_auto_add_header=0
```

```
augroup header
  autocmd!
  autocmd BufNewFile,BufRead *.md,.vimrc
    \ let g:header_auto_add_header = 0 |
    \ let g:header_auto_update_header = 0
augroup end
```

Any idea / suggestion?
