### ISSUE TITLE
function s:update_header_field(field) bug

### ISSUE THREAD

**Issue by TC500** [alpertuna/vim-header#39]
if date format set to %Y:%m:%s and call AddHead twice,the Date field will be 
```
Date: xx
```
not 
```
Date: xx:xx:xx
```
regex in function s:update_header_field(field) should be(replace last '\*' with '{-}'):
```
    let l:field_without_spaces = substitute(a:field, '\s*:$', '\\s*.{-}:', '')
```
this works because use the non greedy match regex

**Comment by alpertuna** [comment]
Thanks for your detailed note. Problem should be fixed now.
 New regex for that part is `'\\s*.[^:]*:'` This is manual non-greedy :) since vim didn't recognize `{-}`
