### ISSUE TITLE
horrible BUG

### ISSUE THREAD

**Issue by lifeyf** [alpertuna/vim-header#40]
THIS plugin just automatically changed my codes
horrible!
fantastic!
unbelievable!

my codes look like this:

 .vimrc  

  1 colorscheme desert
  2 set nocompatible              " be iMproved, required
  3 filetype off              " required
  4 autocmd FileType css set omnifunc=csscomplete "CompleteCSS
  5 autocmd FileType html set omnifunc=htmlcomplete "CompleteTags 
  6 set ruler
  7 set ignorecase
  8 set tabstop=4
  9 set softtabstop=4
 10 set shiftwidth=4
 11 set textwidth=0

**Comment by alpertuna** [comment]
Could you share your file content which cause unintended change?

**Comment by alpertuna** [comment]
Not enough information to fix
