### ISSUE TITLE
absolute path in the `file` field

### ISSUE THREAD

**Issue by Jesse-XIE** [alpertuna/vim-header#47]
I want only the filename in the `file` filed, while I got the whole absolute path instead. Is this configurable?

**Comment by alpertuna** [comment]
It is relative to vim working directory and not configurable for now. But it is possible to add this feature.

**Comment by Lucklyric** [comment]
@Jesse-XIE check my fork:
https://github.com/Lucklyric/vim-header
I added a setting option `g:header_field_filename_path`
Whether put only file name (0) or with its relative path (1).
0 by default.

**Comment by alpertuna** [comment]
Thanks you @Lucklyric
