### ISSUE TITLE
[Feature Request] Some tiny features

### ISSUE THREAD

**Issue by clouduan** [alpertuna/vim-header#50]
Hi @alpertuna, thank you so much for this fantastic plugin!  I manually added file headers until I find this.
Just some tiny features that will make the experience better.

- Jump to the last line automatically after inserting the headers.
In my function I wrote something like `normal G` + `normal o`, and that makes more convenient. So I can type `i` to edit directly, otherwise I have to type 'G' + 'o' +'Enter'...

- Allow user to chose the path of the python
Although python2 will retire after 2020, this path `#!/usr/bin/env python` points to python2 for the most part. https://github.com/alpertuna/vim-header/blob/5a867acc89e7473a95953e26d1b8e79a3f77add3/autoload/header.vim#L105 
In my option, this can be added permanently and canceled  after 2020 :sweat_smile: 

How do you think that?

**Comment by alpertuna** [comment]
Sorry for late reply, I am a little busy.
- You are right about jump issue and I will implement it as you say.
- About python case, do you propose an option field for vimrc that sets python path?

**Comment by clouduan** [comment]
@alpertuna Usually python path is `/usr/bin`, just change `/usr/bin/env python` to `/usr/bin/env python3`.
Does this work?

**Comment by alpertuna** [comment]
It is ok now
