### ISSUE TITLE
how about update modify time?

### ISSUE THREAD

**Issue by zishuaiz** [alpertuna/vim-header#8]
```
if line =~ '^\#\s*\S*Last\smodified:\S*.*$'
            call UpdateTitle()

function UpdateTitle()
    normal m'
    execute '/# *Last modified:/s@:.*$@\=strftime(":\t%Y-%m-%d %H:%M")@'
    normal ''
    normal mk
    execute '/# *Filename:/s@:.*$@\=":\t\t".expand("%:t")@'
    execute "noh"
    normal 'k
    echohl WarningMsg | echo "Successful in updating the copy right." | echohl None
endfunction

```

I am not good at vim lang, this is blog http://essun.blog.51cto.com/721033/1359494
give me the idea, hope you guys can add this func, thanks for your efforts.

**Comment by alpertuna** [comment]
Hi @zishuaiz,
It is a good idea. I will inspect the code. I may add this support soon.

**Comment by alpertuna** [comment]
Hi @zishuaiz 
I finally found time to take care of this support.
I have added "modified date" and "auto add header" support just now.
Both of them are enabled by default and can be disabled.
New settings are `g:header_field_modified_timestamp` and `g:header_auto_add_header`.
Readme parts you may be interested;
- [Examples](https://github.com/alpertuna/vim-header#examples)
- [Settings](https://github.com/alpertuna/vim-header#settings)

For any bug you encounter, you can open issue back
