### ISSUE TITLE
Error occurs when updating vim header

### ISSUE THREAD

**Issue by shoichiaizawa** [alpertuna/vim-header#9]
I have encountered an error when updating header for my `.vimrc`/`vimrc` file.

Executing `:AddHeader` successfully adds header lines if there is no existing header; please see an example below:

```vim
" File: .vimrc
" Author: Firstname Lastname <username@example.com>
" Date: d.m.Y
" Last Modified: d.m.Y

```

But when executing `:AddHeader` to update the header, it fails but delete the "File" and "Last Modified" lines, where updates are supposed to occur; please see an example below:

```vim

" Author: Firstname Lastname <username@example.com>
" Date: d.m.Y


```

I suspect that this error is caused due to the fact that Vim's comment char is(`"`) when calling [`update_header()` function](https://github.com/alpertuna/vim-header/blob/master/autoload/header.vim#L178).

I am not good at Vimscript so I don't know how to fix this.
I hope you can replicate this error.

**Comment by alpertuna** [comment]
Hi @shoichiaizawa,
Thanks for the report. I committed a quick fix for this. You were right, it's because of vim's comment char `"`

**Comment by shoichiaizawa** [comment]
@alpertuna That was a quick fix! Thanks for the update :D
